// components/home/MissionSection.vue
<template>
  <section class="py-24 md:py-32 bg-cream relative overflow-hidden">
    <!-- Decorative circles -->
    <div class="absolute -top-32 -right-32 w-96 h-96 rounded-full opacity-5 bg-gold-500 pointer-events-none" />
    <div class="absolute -bottom-32 -left-32 w-80 h-80 rounded-full opacity-5 bg-terra-500 pointer-events-none" />

    <div class="relative max-w-7xl mx-auto px-6 lg:px-8">

      <!-- Header -->
      <div ref="headerEl" :class="['reveal mb-16', headerVisible && 'visible']">
        <span class="section-label mb-4">Vores Mission</span>
        <div class="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-6 mt-4">
          <h2 class="font-serif font-bold text-3xl sm:text-4xl md:text-5xl text-terra-900 max-w-2xl leading-tight">
            At Åbenbare Guds Kærlighed &amp;
            <span class="text-gold-600">Demonstrere Hans Kraft</span>
          </h2>
          <p class="text-warm-400 text-sm italic max-w-xs leading-relaxed">
            Mark 12:30 — Elsk Herren din Gud af hele dit hjerte
          </p>
        </div>
      </div>

      <!-- Value cards -->
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5 mb-6">
        <div
          v-for="(v, i) in values"
          :key="v.title"
          :ref="el => valEls[i] = el as Element"
          :class="['reveal card p-6 group', valVisible[i] && 'visible', `delay-${i * 100 + 100}`]"
        >
          <div class="w-12 h-12 rounded-2xl flex items-center justify-center mb-5 transition-transform duration-300 group-hover:scale-110"
            :class="v.bgClass">
            <component :is="v.icon" class="w-5 h-5" :class="v.iconClass" />
          </div>
          <h3 class="font-serif font-semibold text-terra-900 text-base mb-2">{{ v.title }}</h3>
          <p class="text-warm-500 text-sm leading-relaxed">{{ v.desc }}</p>
        </div>
      </div>

      <!-- Vision strip -->
      <div ref="visionEl" :class="['reveal card p-8 md:p-10 bg-terra-900 text-white', visionVisible && 'visible delay-400']">
        <p class="text-xs uppercase tracking-widest text-white/40 mb-7 font-semibold">Vores Vision</p>
        <div class="grid grid-cols-1 sm:grid-cols-3 gap-8">
          <div v-for="(item, i) in vision" :key="item.label" class="flex items-start gap-4">
            <span class="flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold text-terra-900 mt-0.5"
              style="background: linear-gradient(135deg, #e8c76a, #c9a84c)">
              {{ i + 1 }}
            </span>
            <div>
              <p class="font-semibold text-white text-sm mb-1">{{ item.label }}</p>
              <p class="text-white/50 text-sm leading-relaxed">{{ item.desc }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { Heart, Zap, Globe, Users } from 'lucide-vue-next'

const values = [
  { icon: Heart, title: 'Guds Kærlighed',  desc: 'Vi tror på en Gud der elsker alle uanset baggrund eller fortid.', bgClass: 'bg-terra-50', iconClass: 'text-terra-500' },
  { icon: Zap,   title: 'Hans Kraft',      desc: 'Vi oplever og forkynder Guds kraft — helbredelse og mirakler.', bgClass: 'bg-gold-50', iconClass: 'text-gold-600' },
  { icon: Globe, title: 'Internationalt',  desc: 'Folk fra over 10 nationaliteter. 4 sprog i vores gudstjenester.', bgClass: 'bg-warm-100', iconClass: 'text-warm-600' },
  { icon: Users, title: 'Forbundne Liv',   desc: 'Vi forbinder mennesker med Gud og hinanden i kaldet.', bgClass: 'bg-cream', iconClass: 'text-terra-400' },
]

const vision = [
  { label: 'Forbinde', desc: 'Mennesker med Gud og hinanden' },
  { label: 'Udruste',  desc: 'Til at leve i deres gudgivne kald' },
  { label: 'Nå Ud',    desc: 'Lokalt og globalt med evangeliet' },
]

const { el: headerEl, isVisible: headerVisible } = useReveal()
const { el: visionEl, isVisible: visionVisible } = useReveal()
const valEls = ref<Element[]>([])
const valVisible = ref([false, false, false, false])

onMounted(() => {
  valEls.value.forEach((el, i) => {
    if (!el) return
    const obs = new IntersectionObserver(([e]) => {
      if (e.isIntersecting) { valVisible.value[i] = true; obs.disconnect() }
    }, { threshold: 0.1 })
    obs.observe(el)
  })
})
</script>

// components/home/MissionSection.tsx
"use client";

import { motion } from "framer-motion";
import { Heart, Zap, Globe, Users } from "lucide-react";

const values = [
  {
    icon: Heart,
    title: "Guds Kærlighed",
    desc: "Vi tror på en Gud der elsker alle uanset baggrund, nationalitet eller fortid.",
    color: "text-cyan-400",
    bg: "bg-cyan-500/10",
    border: "border-cyan-500/20",
    glow: "rgba(6,182,212,0.15)",
  },
  {
    icon: Zap,
    title: "Hans Kraft",
    desc: "Vi oplever og forkynder Guds kraft — helbredelse, mirakler og Ånden i aktion.",
    color: "text-blue-400",
    bg: "bg-blue-500/10",
    border: "border-blue-500/20",
    glow: "rgba(59,130,246,0.15)",
  },
  {
    icon: Globe,
    title: "Internationalt",
    desc: "Folk fra over 10 nationaliteter. Vi taler dansk, engelsk, swahili og spansk.",
    color: "text-sky-400",
    bg: "bg-sky-500/10",
    border: "border-sky-500/20",
    glow: "rgba(14,165,233,0.15)",
  },
  {
    icon: Users,
    title: "Forbundne Liv",
    desc: "Vi forbinder mennesker med Gud og hinanden, og udruster dem til at leve i kaldet.",
    color: "text-indigo-400",
    bg: "bg-indigo-500/10",
    border: "border-indigo-500/20",
    glow: "rgba(99,102,241,0.15)",
  },
];

const visionItems = [
  { label: "Forbinde",  desc: "Mennesker med Gud og hinanden" },
  { label: "Udruste",   desc: "Til at leve i deres gudgivne kald" },
  { label: "Nå Ud",     desc: "Lokalt og globalt med evangeliet" },
];

export function MissionSection() {
  return (
    <section className="py-24 md:py-32 relative overflow-hidden">
      <div className="absolute inset-0 bg-slate-900/35" />
      <div className="absolute top-0 right-0 w-[600px] h-[600px] rounded-full bg-cyan-500/[0.04] blur-[160px] pointer-events-none" />
      <div className="absolute bottom-0 left-0 w-[400px] h-[400px] rounded-full bg-blue-600/[0.04] blur-[130px] pointer-events-none" />

      <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">

        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 28 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.65 }}
          className="mb-16"
        >
          <span className="section-label mb-5 block w-fit">Vores Mission</span>
          <div className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-6">
            <h2 className="text-3xl sm:text-4xl md:text-5xl font-black text-white max-w-2xl leading-tight">
              At Åbenbare Guds Kærlighed &{" "}
              <span className="gradient-text">Demonstrere Hans Kraft</span>
            </h2>
            <p className="text-slate-500 text-sm max-w-xs lg:text-right leading-relaxed flex-shrink-0 italic">
              Mark 12:30 — Elsk Herren din Gud af hele dit hjerte
            </p>
          </div>
        </motion.div>

        {/* Value cards */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-5">
          {values.map((v, i) => (
            <motion.div
              key={v.title}
              initial={{ opacity: 0, y: 36 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1, duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
              whileHover={{ y: -6, transition: { duration: 0.2 } }}
              className="card p-6 group cursor-default"
            >
              {/* Icon */}
              <div className="relative mb-5">
                <div
                  className={`w-12 h-12 rounded-2xl ${v.bg} border ${v.border} flex items-center justify-center group-hover:scale-110 transition-transform duration-300`}
                >
                  <v.icon className={`w-5 h-5 ${v.color}`} />
                </div>
                {/* Glow on hover */}
                <div
                  className="absolute inset-0 w-12 h-12 rounded-2xl opacity-0 group-hover:opacity-100 blur-xl transition-opacity duration-500"
                  style={{ background: v.glow }}
                />
              </div>
              <h3 className="text-white font-bold text-base mb-2.5">{v.title}</h3>
              <p className="text-slate-500 text-sm leading-relaxed">{v.desc}</p>
            </motion.div>
          ))}
        </div>

        {/* Vision strip */}
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ delay: 0.3, duration: 0.6 }}
          className="card p-8 md:p-10 relative overflow-hidden"
        >
          <div className="absolute inset-0 bg-gradient-to-r from-cyan-500/[0.04] via-transparent to-blue-500/[0.04] pointer-events-none" />
          <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-cyan-500/25 to-transparent" />
          <p className="text-slate-500 text-xs uppercase tracking-widest mb-8 font-semibold">Vores Vision</p>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-8">
            {visionItems.map((item, i) => (
              <div key={item.label} className="flex items-start gap-4">
                <span className="flex-shrink-0 w-8 h-8 rounded-full bg-gradient-to-br from-cyan-500/20 to-blue-600/20 border border-cyan-500/25 text-cyan-400 text-sm font-black flex items-center justify-center mt-0.5">
                  {i + 1}
                </span>
                <div>
                  <p className="text-white font-bold text-sm mb-1">{item.label}</p>
                  <p className="text-slate-500 text-sm leading-relaxed">{item.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </motion.div>

      </div>
    </section>
  );
}
